baseURL = 'https://gomooc.github.io/blog/'
DefaultContentLanguage = "zh"
languageCode = 'en-us'
title = 'é²¸äº‘'
theme = ["hugo-embed-pdf-shortcode", "archie"]
enableInlineShortcodes = true
copyright = "ç‰ˆæƒ@gomooc"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "å®‰é™ğŸ¤«å¹³å’Œ"
favicon = "https://icons.bootcss.com/assets/icons/cpu-fill.svg"
enableLaTeX = true


# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "åˆ†ç±»"
weight = 2
[[menu.main]]
url = "/tags"
name = "æ ‡ç­¾"
weight = 3
[[menu.main]]
url = "/posts"
name = "å½’æ¡£"
weight = 1

[markup.goldmark.renderer]
    unsafe = true

